// Generated by delombok at Tue Dec 17 14:57:07 CET 2019
package com.boringville.sscce.lombok.onparam;

import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;

@NonNullByDefault
public class TestCaseDelomboked {
	/*
	 * Delombok incorrectly generates this message signature as
	 *
	 * "protected boolean canEqual(@Nullable final java.lang.Object other) {"
	 *
	 * With the reordered signature it compiles and works correctly.
	 */
	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.@Nullable Object other) {
		return other instanceof TestCaseDelomboked;
	}

	/*
	 * Delombok incorrectly generates this message signature as
	 *
	 * "public boolean equals(@Nullable final java.lang.Object o) {"
	 *
	 * With the reordered signature it compiles and works correctly.
	 */
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.@Nullable Object o) {
		if (o == this)
			return true;
		if (!(o instanceof TestCaseDelomboked))
			return false;
		final TestCaseDelomboked other = (TestCaseDelomboked) o;
		if (!other.canEqual(this))
			return false;
		return true;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int result = 1;
		return result;
	}
}
